### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**
With help of MailGik, Russian translation is 100% complete. Closes #37

### CODE REVIEW

**Comment by RestBrains** [comment]
This translation is wrong in many places. Think before you commit.

**Comment by labpaw** [comment]
No, it's correct.

**Comment by labpaw** [comment]
@Pokefenn are you going to pull it?

**Comment by Pokefenn** [comment]
Yup, just had some other stuff to do.

**Pull request merged**
