### PR TITLE
Added Waila Integration

### PR DESCRIPTION
**Pull request by Parker8283**
The variation description is shown in between the block name and the mod name. Quite handy. Also some other minor improvements:
- Added IDEA files to gitignore, for people who use IDEA (like me)
- Replaced deprecated `assetDir` with `runDir`
- Allowed for version replacing upon build, making it so you only have to change the version number in one place for each update, instead of two.
- Changed API Zip to Sources Jar, as that will probably be used more often anyway.
- Formatting and other small things, just look at the changes.

### CODE REVIEW

**Comment by Pokefenn** [comment]
Looks good, nice idea ;D
Will merge it soon.

**Comment by EoD** [comment]
If you could split up your commit into smaller commits (like one for gitignore, one for assetDir replacement, etc) then I would be interested in merging it into my 1.7.2 branch of Chisel.

**Comment by Parker8283** [comment]
I don't care about 1.7.2 anymore. That was a buggy as hell version of Minecraft.

**Comment by Pokefenn** [comment]
Yeah... 1.7.2 is broken, unsupported and completely deprecated now.
There is 0 reason to ever be running it.

**Pull request merged**
