### PR TITLE
Fixed ArrayIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by dariusc93**
This PR fixes a ArrayIndexOutOfBoundsException that occurs when you place any block into the center of the chisel. This is due to the OreDictionary.getOreID() returning -1. By adding this small check in, it insures if it returns -1 or 0, to return null to prevent this crash. 

Original crash log : http://pastebin.com/J0XxuZi8

I also updated to the latest version of forge (1.7.2-10.12.2.1123 is recommended but I pushed to 1.7.2-10.12.2.1124), and change how the OreDictionary.getOreID() is used in this code by using a name instead of an ItemStack (OreDictionary.getOreID(ItemStack) is deprecated and will likely be removed in the 1.7.10 update so if you do switch back, keep in mind that it will be removed)

### CODE REVIEW

**Comment by dariusc93** [comment]
Base off the recent commits, it look like the changes was merged to fix the issue (hopefully).

**Comment by Pokefenn** [comment]
Yeah, i couldnt reproduce the issue after doing my change.
I just didn't see this commit until after i pushed it xD

**Comment by dariusc93** [comment]
Lol well atleast its fixed. I would recommend that you do add a check in to make sure it does not return -1 or 0 (incase for some odd reason the OreDictionary returns nothing).

**Comment by dariusc93** [comment]
@Pokefenn you can update to 1126.

http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.2-10.12.2.1126/forge-1.7.2-10.12.2.1126-changelog.txt

**Pull request closed without merging**
