### PR TITLE
add chisel compatibility for Geologica marble and limestone

### PR DESCRIPTION
**Pull request by lawremi**

### CODE REVIEW

**Comment by Pokefenn** [comment]
Heya, would you be able to change it to use https://github.com/Pokefenn/Chisel/blob/master/src/main/java/info/jbcs/minecraft/chisel/Compatibility.java#L15 instead? Thanks

**Comment by lawremi** [comment]
Ported things over. If you could help with the stairs group, that would be great. I've got the wrong name for it.

**Comment by EoD** [comment]
You want to rebase your commits instead of reverting them. Have a look at https://help.github.com/articles/about-git-rebase/

**Comment by lawremi** [comment]
I can do that if necessary, although I'm not sure I understand the motivation. Why change history? Pokefenn's comment won't make much sense after I do that.

**Comment by EoD** [comment]
That's what you do in git if you finished a feature/bugfix branch and want to merge it into master. An excerpt from http://git-scm.com/book/en/Git-Branching-Rebasing (read the full article if you want to know more details):
`Often, you’ll do this to make sure your commits apply cleanly on a remote branch — perhaps in a project to which you’re trying to contribute but that you don’t maintain. In this case, you’d do your work in a branch and then rebase your work onto origin/master when you were ready to submit your patches to the main project. That way, the maintainer doesn’t have to do any integration work — just a fast-forward or a clean apply.`

His comment still makes sense because everyone can read all the other comments in here and see what happened.

**Comment by lawremi** [comment]
This pull request is still automatically mergeable, so I'm not sure that's justification, but if Pokefenn requests it, I'll gladly oblige.

**Comment by Pokefenn** [comment]
I see no reason to change it, will go over it properly tomorrow though incase i'm missing something, heh :p (Sorry, IRL stuff got in the way over the weekend)

**Pull request merged**
