### PR TITLE
1.7.10 port, Finished Localizations(almost!), Config GUI's, Typo Fixes

### PR DESCRIPTION
**Pull request by ghost**
As the title implies, this is kind of a big pr, and as a result may contain bugs (especially with that config gui- not even sure if I did that right).

This MAY break SOME blocks in 1.7.2 worlds, as they had to be renamed for the sake of localizations.  Testing probably should be done as to assess the damage.

Basically, this adds a requested feature and cleans a few rough spots.  This should be reviewed before being merged.

### CODE REVIEW

**Comment by Pokefenn** [comment]
Had a quick look over it, and it looks good.
Will have a proper overview of it when I'm not half asleep (just woke up <,<)
So yeah, :D

**Comment by ghost** [comment]
Really; just woke up?  I should be asleep right now :P
But yeah, just needs the localization finished, which is a real pain...

**Comment by Pokefenn** [comment]
That's time zones for ya :P
I can help with the locale if you want, btw :p
I'm not doing anything productive currently xD

**Comment by ghost** [comment]
You can; thats all thats left to finish in the pr.  If you do that, then just go ahead and merge.

I have been doing the locales to distract me from my other huge project... god I have so much to learn to finish that...

**Pull request merged**
