### PR TITLE
1.7.10pre4 Port, Block Localization, Sound Fixes, Slab Fixes

### PR DESCRIPTION
**Pull request by ghost**
~~What I have been intending to do.~~  More than what I intended I was going to do.  Not quite ready yet, but everything is in place- I just need time.

Will close issues #15, #16, #12, #14

### CODE REVIEW

**Comment by Pokefenn** [comment]
Looks great, will merge once i get 1.7.10 in order :)

**Comment by ghost** [comment]
Already updated to 1.7.10pre4 on my fork; if that is okay with you (will revert if necessary).

Edit: Oooh! Realized I fixed #12 as well!  It is almost as if I am fixing everything :P

Edit 2: Found a pretty nasty bug regarding stair descriptions; has to do with descriptions being assigned by metadata.

**Comment by Pokefenn** [comment]
So, this all good to try to merge? :)

**Comment by ghost** [comment]
Uhhh.... wasn't quite done yet.  I will make another once it is.

I was kinda holding off because I found a pretty bad bug with stair descriptions and was trying to fix it, but I will finish the other blocks and make another one for then.  I will try to address the stair problem later.

**Comment by Pokefenn** [comment]
<,< 
I'm a moron, sorry about that.

**Comment by ghost** [comment]
No problem!  Although input on the stairs bug would be appreciated.

Edit: Should probably explain what is going on.  Descriptions are assigned to blocks via metadata, right?  So it works perfectly fine with all the blocks currently in the mod.  The issue with stairs, however, is that they take up multiple metadata positions because of their different states- 8 to be exact.  So, what is happening is that the stairs are grabbing the descriptions assigned to metadata 0 and 8, but none of the others in between.

I have been trying to find a workaround, but I honestly don't know how it will be fixed without some significant changes.

**Comment by Pokefenn** [comment]
Ah... hrm.
It's not too much of a major bug, so i think its something that can be left until a suitable way is found :p

**Comment by ghost** [comment]
Alrighty then, let me pull in your changes and finish the blocks.  Will make a seperate pr when I am ready (again).

**Pull request merged**
